#!/bin/bash

## TODO: add dvd episodes || this is a dirty one-liner test 
#for i in `seq 4`; do ./handbrake --input /Volumes/E1587/ --title $i --preset Normal --output ~/Desktop/NameOfDisc_Title$i.mp4; done

# Change independent field seperator
SAVEIFS=$IFS
IFS=$'\n'

APP_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
APP_NAME="$(basename "$0")"
BASE_APP_PATH=`echo $APP_PATH | sed -e 's/Contents\/MacOS//g'`
DATE=`date +%Y%m%d-%H%M%S`

# Check for preferred notifier.
check_gem=`gem list terminal-notifier -i`

## Create functions for repetitious work
# Notification functions
function success_completion () {
  if [[ $check_gem == "true" ]]; then
    echo "Completed all files" | terminal-notifier -title $APP_NAME -sound default -contentImage "$BASE_APP_PATH/Contents/Resources/$APP_NAME.icns"
  else
    osascript -e "display notification \"Completed all files\" with title \"$APP_NAME\""
  fi
}
function success () {
  if [[ $check_gem == "true" ]]; then
    echo "Completed: $@" | terminal-notifier -title $APP_NAME -contentImage "$BASE_APP_PATH/Contents/Resources/$APP_NAME.icns"
  else
    osascript -e "display notification \"Completed: $@\" with title \"$APP_NAME\""
  fi
}
function killed () {
  if [[ $check_gem == "true" ]]; then
    echo "$APP_NAME Killed" | terminal-notifier -title $APP_NAME -sound Basso -contentImage "$BASE_APP_PATH/Contents/Resources/$APP_NAME.icns"
  else
    osascript -e "display notification \"$APP_NAME Killed\" with title \"$APP_NAME\""
  fi
}
function failure () {
  if [[ $check_gem == "true" ]]; then
    echo "Failed: $@" | terminal-notifier -title $APP_NAME -sound Basso -contentImage "$BASE_APP_PATH/Contents/Resources/$APP_NAME.icns"
  else
    osascript -e "display notification \"Failed: $@\" with title \"$APP_NAME\""
  fi
}
function error {
  if [[ $check_gem == "true" ]]; then
    echo "Exiting: Error" | terminal-notifier -title $APP_NAME -sound Basso -contentImage "$BASE_APP_PATH/Contents/Resources/$APP_NAME.icns"
  else
    osascript -e "display notification \"Exiting: Error\" with title \"$APP_NAME\""
  fi
}
# Misc work and Errors
function cut_string () {
  echo $@ | cut -d ":" -f 2
}
function check_removal () {
  if [[ $? == 1 ]]; then
    IFS=$SAVEIFS
    exit 1
  fi
}
function check_bool () {
  if [[ $? == 1 ]]; then
    IFS=$SAVEIFS
    error
    exit 1
  fi
}
function kill_app () {
  pids=`ps -ef | grep $APP_NAME | grep "/bin/bash" | awk '{print $2}'`
  for pid in $pids; do
    kill $pid
    killed
    IFS=$SAVEIFS
    exit 0
  done
}

# Prompt for file/folder input
input_selector=`osascript -e 'tell app "System Events" to display dialog "Select a File or Folder?" buttons {"Kill","Folder","File"} default button 3 with title "'$APP_NAME'" with icon {"'$BASE_APP_PATH'/Contents/Resources/'$APP_NAME'.icns"}'` 
check_bool $input_selector
input_selection=`cut_string $input_selector`

# Do a check for input selection file/folder and create array
if [[ $input_selection == "File" ]]; then
  files=`osascript -e 'tell application "System Events" to return POSIX path of (choose file)'`
  check_bool $files
  file_list=`find "$files"`
  input_directory=`dirname "$files"`
elif [[ $input_selection == "Folder" ]]; then
  files=`osascript -e 'tell application "System Events" to return POSIX path of (choose folder)'`
  check_bool $files
  file_list=`find "$files" -iname "*.mkv" -o -iname "*.mp4" -o -iname "*.mpg" -o -iname "*.avi"`
  input_directory="$files"  
elif [[ $input_selection == "Kill" ]]; then
  kill_app
fi

# Prompt for folder output
output_selector=`osascript -e 'tell app "System Events" to display dialog "Select Output Directory. (Default:Input)" buttons {"Cancel","Select","Default"} default button 3 with title "'$APP_NAME'" with icon {"'$BASE_APP_PATH'/Contents/Resources/'$APP_NAME'.icns"}'`
check_bool $output_selector
output_selection=`cut_string $output_selector`

# Do a check for output selection default/other
if [[ $output_selection != "Default" ]]; then 
  output_directory=`osascript -e 'tell application "System Events" to return POSIX path of (choose folder)'`
  check_bool $output_directory
fi

preset=`osascript -e 'tell application "System Events" to activate' -e 'tell application "System Events" to return (choose from list { "Universal", "iPod", "iPhone & iPod Touch", "iPad", "AppleTV", "AppleTV 2", "AppleTV 3", "Android", "Android Tablet", "Normal", "High Profile" } with prompt "Choose a Preset" with title "Preset Selector" OK button name "Select" cancel button name "Quit")'`
prompt_extension=`osascript -e 'tell app "System Events" to display dialog "Select Output Extension." buttons {"mkv","mp4"} default button 2 with title "'$APP_NAME'" with icon {"'$BASE_APP_PATH'/Contents/Resources/'$APP_NAME'.icns"}'`
extension=`cut_string $prompt_extension`

# Do the work
for file in $file_list; do
  if [[ $output_selection == "Default" ]]; then
    output_directory=`dirname $file`
  fi  
  base_filename=`basename $file`
  dest_filename="${base_filename%.***}.$extension"
  if [ -f $output_directory/${dest_filename} ];
    then dest_filename="${base_filename%.***}.${DATE}.$extension"
  fi
  $BASE_APP_PATH/Contents/Resources/bin/handbrake -i "$file" -o $output_directory/"${dest_filename}" --preset="$preset" > $BASE_APP_PATH/Contents/Resources/tmp/$base_filename.txt
  check_bool
  success "${base_filename%.***}.$extension"
  rm -f $BASE_APP_PATH/Contents/Resources/tmp/$base_filename.txt
done

success_completion

IFS=$SAVEIFS

exit 0